package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPartner;
import org.linlinjava.litemall.db.domain.LitemallPartnerExample;
import org.linlinjava.litemall.db.domain.LitemallPartnerSelect;

public interface LitemallPartnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    long countByExample(LitemallPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int insert(LitemallPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    LitemallPartner selectOneByExample(LitemallPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    LitemallPartner selectOneByExampleSelective(@Param("example") LitemallPartnerExample example, @Param("selective") LitemallPartner.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    List<LitemallPartner> selectByExampleSelective(@Param("example") LitemallPartnerExample example, @Param("selective") LitemallPartner.Column ... selective);

    List<LitemallPartner> selectPartnerDistance(LitemallPartnerSelect examle);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    List<LitemallPartner> selectByExample(LitemallPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    LitemallPartner selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPartner.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    LitemallPartner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    LitemallPartner selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPartner record, @Param("example") LitemallPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPartner record, @Param("example") LitemallPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPartner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallPartnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_partner
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}